repos:
-   repo: local
    hooks:
    -   id: requirements
        name: requirements
        entry: bash -c '. .venv/Scripts/activate pip freeze > requirements.txt ; git add *'
        language: system
        pass_filenames: false
        stages: [commit]